apiVersion: litellm.litellm.ai/v1alpha1
kind: LiteLLMInstance
metadata:
  name: litellm-prod
  namespace: litellm
spec:
  redisSecretRef:
    nameRef: redis-secret
    keys:
      hostSecret: host
      portSecret: port
      passwordSecret: password

  databaseSecretRef:
    nameRef: postgres-secret
    keys:
      hostSecret: host
      usernameSecret: username
      passwordSecret: password
      dbnameSecret: dbname

  models:
    - modelName: llama3.2-1b
      identifier: llama3.2-1b-local
      requiresAuth: false
      liteLLMParams:
        model: ollama/llama3.2:1b
        api_base: http://ollama:11434
