apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: litellm
type: Opaque
stringData:
  host: postgres.example.svc.cluster.local
  username: litellm
  password: password123
  dbname: litellm